name: jojo
description: "Soundboard"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.6
  audioplayers: ^5.2.1
  share_plus: ^7.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/0/
    - assets/sounds/1/
    - assets/sounds/2/
    - assets/sounds/3/
    - assets/sounds/4/
    - assets/sounds/5/
    - assets/sounds/6/
    - assets/images/jojo/
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
